# Base configs
baseurl: "https://clicksnsketches.github.io"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Anik Debnath"
subtitle: "See the world through my eyes!"
author: "Anik Debnath"
header:
 title: "Photography"
 subtitle: "by Anik Debnath"
footer:
 name: "Hey there, my name is Anik"
 bio: "I love to click & draw, mechanical engineer by profession. Here you will will find my travel & wildlife photography"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/rampatra/photography\">fork this repo on github</a> ;)"
web_design: "AD"

social_urls:
  twitter: ""
  instagram: "https://www.instagram.com/clicks_n_sketches"
  facebook: "https://www.facebook.com/clicksnsketches"
  linkedin: ""
  github: "https://www.github.com/clicksnsketches"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
