# Base configs
baseurl: "https://clicksnsketches.github.io"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Anik Debnath"
subtitle: "See the world through my eyes!"
author: "Anik Debnath"
header:
 title: "Photography"
 subtitle: "by Anik Debnath"
footer:
 name: "Hey there, my name is Anik"
 bio: "By day, I speak the language of gears, machines and precision. But my heart speaks in light, shadow and ink. ​Here, From the raw, untamed silence of the wildlife reserves to the vibrant chaos of my travels, this is my archive of frozen time. ​Welcome to my world, where the structured mind meets the wandering soul."
 
web_design: "AD"

social_urls:
  instagram: "https://www.instagram.com/clicks_n_sketches"
  facebook: "https://www.facebook.com/clicksnsketches"
  github: "https://www.github.com/clicksnsketches"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
